### ISSUE TITLE
Install Niko connector on hass.io

### ISSUE THREAD

**Issue by jwmaas** [NoUseFreak/niko-home-control#1]
I'd like to test the Niko connector, but it is unclear from the documentation and discussions how to install on hass.io. Do I install as custom component? Which files to go where? Many thanks. On hass.io only the config directory is easily accessible and will not be overwritten.

**Comment by NoUseFreak** [comment]
The current integration in HA is broken, a new PR is in progress. Once merged the next HA release should be working and you should be able to enable it by just setting the host to your nhc controller.

**Comment by NoUseFreak** [comment]
@jwmaas The update/working integration was merged into version `0.92.0b2` of home-assistant.
After install home-assistant, just add the following to your config.
https://www.home-assistant.io/components/niko_home_control/
