### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by pergolafabio** [NoUseFreak/niko-home-control#8]
Hi, we still have the error below, even with 92.0
NHC version 1

2019-05-07 21:29:07 ERROR (MainThread) [homeassistant.components.light] Error while setting up platform niko_home_control
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/niko_home_control/light.py", line 43, in async_setup_platform
    NikoHomeControlLight(light, niko_data) for light in nhc.list_actions()
  File "/usr/local/lib/python3.7/site-packages/nikohomecontrol/nikohomecontrol.py", line 36, in list_actions
    return [Action(action, self) for action in self.list_actions_raw()]
  File "/usr/local/lib/python3.7/site-packages/nikohomecontrol/nikohomecontrol.py", line 36, in <listcomp>
    return [Action(action, self) for action in self.list_actions_raw()]
  File "/usr/local/lib/python3.7/site-packages/nikohomecontrol/nikohomecontrol.py", line 77, in __init__
    self._id = action['id']
TypeError: string indices must be integers

**Comment by NoUseFreak** [comment]
@pergolafabio Hi, sorry to hear it's not working for you.

Could you check what the following setup gives if we use just the hnc repo?

```
mkdir /tmp/testing
cd /tmp/testing
pip3 install venv
python3 -m venv .venv
source .venv/bin/activate
pip3 install niko-home-control==0.2.1
```

test.py
```
from nikohomecontrol import NikoHomeControl

nhc = NikoHomeControl({
	'ip': '<your_nhc_ip>',
	'port': 8000,
	'timeout': 20000,
	'events': True
})

for action in nhc.list_actions_raw():
    print(action)
```

```
python3 test.py
```

Could you share the output.

**Comment by vincentvanneer** [comment]
@NoUseFreak 

Hi Dries

I did some testing and can inform you about the results.

I was able to install NHC using the command (pip3 install niko-home-control==0.2.1)

I then tried to run the test.py but received an error. I looked in the class and methods of your solution and also tried to call some other methods. None of them worked.

When I opened Putty and connected to my NHC on port 8000, using TELNET, I was able to paste the commands and I received information from my installation. 

For example. When I pasted the command {"cmd":"listactions"} I received this in the putty terminal:

{"cmd":"listactions"}
{"cmd":"listactions","data":[ {"id":16,"name":"Ledstrip keukeneiland","type":1,"location":4,"value1":0},{"id":22,"name":"Toilet gelijkvloers","type":1,"location":2,"value1":0},{"id":23,"name":"Technische ruimte","type":1,"location":3,"value1":0},{"id":25,"name":"Alles uit","type":0,"location":5,"value1":0},{"id":55,"name":"Thuiskomen","type":0,"location":5,"value1":0},{"id":33,"name":"Spots zithoek","type":2,"location":5,"value1":0},{"id":34,"name":"Automatische verlichting","type":1,"location":1,"value1":0},{"id":40,"name":"Stopcontact living","type":1,"location":5,"value1":0},{"id":42,"name":"Spots speelruimte","type":2,"location":5,"value1":0},{"id":43,"name":"Verlichting eetplaats","type":2,"location":5,"value1":0},{"id":44,"name":"Verlichting berging","type":1,"location":6,"value1":0},{"id":49,"name":"TV kijken","type":1,"location":5,"value1":0},{"id":50,"name":"Zwembadpomp","type":1,"location":8,"value1":100},{"id":51,"name":"Zwembadverlichting","type":1,"location":8,"value1":0},{"id":52,"name":"Buitenverlichting poolhouse","type":1,"location":8,"value1":0},{"id":54,"name":"Verlichting garage","type":1,"location":7,"value1":0},{"id":56,"name":"Verlichting keukeneiland","type":2,"location":4,"value1":100},{"id":61,"name":"Koken","type":1,"location":4,"value1":0}]}


I was also able to turn on and off my devices using the correct ID.

For example. When I entered: {"cmd": "executeactions","data":[{"id":16,"value1":100}]}

my kitchen ledstrip turned on immedialtely. I also noticed the change of the value when I reran the {"cmd":"listactions"}

The same when I ran: {"cmd": "executeactions","data":[{"id":16,"value1":0}]}

Kitchen ledstrip turned off

For my dimmers I figured out that I could use:

{"cmd":"executeactions","data":[{"id":56,"value1":10, "value2":0}]}
{"cmd":"executeactions","data":[{"id":56,"value1":20, "value2":0}]}
{"cmd":"executeactions","data":[{"id":56,"value1":30, "value2":0}]}
{"cmd":"executeactions","data":[{"id":56,"value1":40, "value2":0}]}
{"cmd":"executeactions","data":[{"id":56,"value1":50, "value2":0}]}
{"cmd":"executeactions","data":[{"id":56,"value1":60, "value2":0}]}
{"cmd":"executeactions","data":[{"id":56,"value1":70, "value2":0}]}
{"cmd":"executeactions","data":[{"id":56,"value1":80, "value2":0}]}
{"cmd":"executeactions","data":[{"id":56,"value1":90, "value2":0}]}
{"cmd":"executeactions","data":[{"id":56,"value1":100, "value2":0}]}

And

{"cmd":"executeactions","data":[{"id":56,"value1":0, "value2":0}]}

To turn them off.

Hope this can help you. 

I think it's somewhere in the way the commands are send to the NHC controller.

I tried different ways to get it working but for now, it only worked using putty and connect with telnet

Kind regards

Vincent

**Comment by vincentvanneer** [comment]
This is the sysinfo by the way:

{"cmd":"systeminfo"}
{"cmd":"systeminfo","data":{"swversion":"1.3.2.38","api":"1.21","time":"20190515154115","language":"NL","currency":"EUR","units":0,"DST":3600,"TZ":3600,"lastenergyerase":"","lastconfig":"20190125185345"}}

**Comment by NoUseFreak** [comment]
@vincentvanneer Could you share some errors you get when running the test.py file. 

I expect something it can't handle in the result it's getting.
It points to some case where the raw action is not an object but a string.

Would you mind printing the value of `action` in the `__init__` method of Action.

 ```
class Action:
    def __init__(self, action, hub):
        print(action)
        self._id = action['id']
        self._state = action
        self._hub = hub```
